import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bethany EC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <h1 className={styles.title}>
        {"Welcome to Bethany English Congregation"}
      </h1>

      <p className={styles.description}>
        {"We're glad you're here."}
      </p>


      <main className={styles.main}>


      </main>
    </div >
  )
}
